// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLJ3VjpWn87H8GJNS6OJiWjQH9lyQHHIQ',
    appId: '1:320216541241:web:ad4891a123847ef87a45e8',
    messagingSenderId: '320216541241',
    projectId: 'fir-auth-e66da',
    authDomain: 'fir-auth-e66da.firebaseapp.com',
    storageBucket: 'fir-auth-e66da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Dg_sJ3rjSpI48kG-GgZswhJUR_p2lTY',
    appId: '1:320216541241:android:d6af21677342e59e7a45e8',
    messagingSenderId: '320216541241',
    projectId: 'fir-auth-e66da',
    storageBucket: 'fir-auth-e66da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmHPShBWnxmxLPOeXm4prFRzRa6_UpFRM',
    appId: '1:320216541241:ios:88217a000d9d15ea7a45e8',
    messagingSenderId: '320216541241',
    projectId: 'fir-auth-e66da',
    storageBucket: 'fir-auth-e66da.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmHPShBWnxmxLPOeXm4prFRzRa6_UpFRM',
    appId: '1:320216541241:ios:88217a000d9d15ea7a45e8',
    messagingSenderId: '320216541241',
    projectId: 'fir-auth-e66da',
    storageBucket: 'fir-auth-e66da.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );
}
